### ISSUE TITLE
Event dates

### ISSUE THREAD

**Issue by cdelcher** [UK-IPOP/open-data-pipeline#16]
Event dates in Milwaukee data not standardized so date functions not working

**Comment by nanthony007** [comment]
Is this an issue where dates are correct but sometimes formatted differently within the same (Milwaukee) dataset? I.e. year-month-day and day-month-year?

**Comment by cdelcher** [comment]
Event dates are messy but many can be restored by pulling off first part of string.  the death month, death day and death year are not calculating correctly, because death date looks like it is always jan 1 1970
