### ISSUE TITLE
id column missing header in connecticut data

### ISSUE THREAD

**Issue by cdelcher** [UK-IPOP/open-data-pipeline#28]
Not sure if other cities have the same issue, but missing header makes pivoting in excel difficult

**Comment by nanthony007** [comment]
please provide screenshot :)

**Comment by cdelcher** [comment]
![image](https://github.com/UK-IPOP/open-data-pipeline/assets/47455867/5a93c912-8270-42eb-a368-4a3ef2509d33)

**Comment by nanthony007** [comment]
For some reason this applies to everything _except_ CookCounty

**Comment by nanthony007** [comment]
Actually it doesn't affect MIL as well. 

This makes me think the "common denominator" involves geocoding.

**Comment by nanthony007** [comment]
Reopened issue until confirmed working in prod

**Comment by nanthony007** [comment]
FIXED :)
