### ISSUE TITLE
Docker image unauthorized

### ISSUE THREAD

**Issue by yalbal4** [UK-IPOP/open-data-pipeline#42]
The command docker pull ghcr.io/uk-ipop/opendata-pipeline:latest gives "Error response from daemon: Head "https://ghcr.io/v2/uk-ipop/opendata-pipeline/manifests/latest": unauthorized"

https://github.com/UK-IPOP/open-data-pipeline/pkgs/container/opendata-pipeline was given as where to pull the image, but this link doesn’t lead anywhere. And when trying to use docker pull for the image, I get unauthorized, which is unexpected for a public image.

**Comment by nanthony007** [comment]
Hello @yalbal4 and thanks for your issue. Apologies for the delayed response. I think the Docker container was private, but that should now be fixed. Apologies for the inconvenience. Please let me know if this resolves the issue.

**Comment by yalbal4** [comment]
Yes, this is resolved. Thank you!
