### ISSUE TITLE
pipeline

### ISSUE THREAD

**Issue by cdelcher** [UK-IPOP/open-data-pipeline#46]
having some trouble with importing the CSV file with SAS and I think it may be unpredictable comma issues in free text.  how difficult would it be to create pipedelimited versions too?

**Comment by nanthony007** [comment]
Which csv file is this referring to @cdelcher?

**Comment by cdelcher** [comment]
I noticed in Milwaukee but haven’t checked the others closely.
Chris Delcher, PhD

On Nov 15, 2024, at 12:39 PM, Nick Anthony ***@***.***> wrote:

﻿
CAUTION: External Sender


Which csv file is this referring to @cdelcher<https://github.com/cdelcher>?

**Comment by cdelcher** [comment]
the pipe doesn't work either but I think I've narrowed down the issue and its just in Milwaukee right now. Any time quotes appear in any of the cause of death fields, the record does not read in properly.  i've eye balled various records and that seems to be consistent.

**Comment by nanthony007** [comment]
Have we come around on this?
