### ISSUE TITLE
misspelling of month

### ISSUE THREAD

**Issue by cdelcher** [UK-IPOP/open-data-pipeline#47]
In the Sacramento file, September is misspelled as Septembe which leads to miscounting if using that field.  The month_num is fine but pointing it out.

**Comment by nanthony007** [comment]
Is this in the 'death_month' field?

**Comment by nanthony007** [comment]
I am unable to replicate this issue on 3 python tools (duckdb, pandas, polars) and R. Please provide more details if possible, seems like it could be another SAS-CSV parsing issue.

**Comment by cdelcher** [comment]
You're right, sorry to bother, my side problem.

Chris Delcher, PhD
Associate Professor
College of Pharmacy
Director, Institute for Pharmaceutical Outcomes and Policy<https://pharmacy.uky.edu/office-research-operations/cornerstones/research-centers/ipop>
University of Kentucky
Google scholar<https://scholar.google.com/citations?user=tBRQWoYAAAAJ&hl=en>
